### ISSUE TITLE
Technical. Integrate Mapster into the application

### ISSUE THREAD

**Issue by Dshauchuk** [Dshauchuk/pango#2]

**Comment by Fulllcrum** [comment]
- Current latest version of Mapster library (7.4.0) does not support .netstandard2.0 anymore, only .netstandard2.1
- UWP does not support .netstandard2.1
![UWPandNextstandart21](https://github.com/Dshauchuk/pango/assets/79802795/93e6835d-4528-448a-a83c-d96046837ca3)
- All other projects in the solution were created as .netstandard2.0 to work with UWP
- The latest version of Mapster, that supports .netstandard2.0 - version 7.3.0

@Dshauchuk **Mapster 7.3.0 will be installed, not the latest version**.
